import type { Metadata } from "next";
import {Manrope} from "next/font/google";
import "./globals.css";



const manrope = Manrope({subsets: ["cyrillic"]});


export const metadata: Metadata = {
  title: "Tap2Go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" style={{scrollBehavior: "smooth"}}>
      <body className={manrope.className + " lg:grid grid-cols-1 justify-items-center text-primaryText"}>
            {children}
      </body>
    </html>
  );
}
