export const cinemas = [
    {
        id: 1,
        name: "ОттегіОттегіОттегіОттегіОттегіОттегіОттегіОттегіОттегіОттегіОттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма", "Комедия", "Мелодрама", "Экшн"],
    },
    {
        id: 2,
        name: "Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі Оттегі ",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма", "Комедия", "Мелодрама", "Экшн"],
    },
    {
        id: 3,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 4,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 5,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 6,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 7,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 8,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 9,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
    {
        id: 10,
        name: "Оттегі",
        rating: 10,
        age: 18,
        image: "/temp/cinema-poster.png",
        genres: ["Триллер", "Драма"],
    },
];

export const theaters = [
    {
        id: 1,
        name: "Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык Бешеный бык ",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма sdsdf sdfds fsd fsdf s о12345asdasd67",
    },
    {
        id: 2,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 3,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 4,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 5,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 6,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 7,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 8,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 9,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },{
        id: 10,
        name: "Бешеный бык",
        age: 18,
        image: "/temp/theater-poster.png",
        price: 8000,
        date: new Date(2022, 10, 10),
        theater: "ARTиШОК",
        description: "Сценический ремейк кинофильма",
    },
];

export const concerts = [
    {
        id: 1,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "КонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцертКонцерт",
    },
    {
        id: 2,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena Almaty Arena Almaty Arena Almaty Arena ",
        description: "Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт ",
    },
    {
        id: 3,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 4,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 5,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 6,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 7,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 8,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 9,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 10,
        name: "Nicole Scherzinger and…",
        age: 18,
        image: "/temp/concert-poster.png",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    }
];

export const others = [
    {
        id: 1,
        name: "Однодневный тур на 5 локаций Однодневный тур на 5 локаций Однодневный тур на 5 локаций Однодневный тур на 5 локаций Однодневный тур на 5 локаций Однодневный тур на 5 локаций Однодневный тур на 5 локаций ",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena Almaty Arena Almaty Arena Almaty Arena Almaty Arena Almaty Arena Almaty Arena Almaty Arena ",
        description: "Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт Концерт ",
    },
    {
        id: 2,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 3,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 4,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 5,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 6,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 7,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 8,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 9,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    },
    {
        id: 10,
        name: "Однодневный тур на 5 локаций",
        age: 18,
        image: "/temp/other-poster.jfif",
        price: 8000,
        date: new Date(2022, 4, 16),
        place: "Almaty Arena",
        description: "Концерт",
    }
]